services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "1323:1323"
    networks:
      - app-network
    environment:
      - APP_ENV=development
    volumes:
      - .:/app
  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-dev
    ports:
      - "5173:5173"
    environment:
      - APP_ENV=development
    volumes:
      - .:/app
  front-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: node-dev-test
    environment:
      - APP_ENV=test
    volumes:
      - .:/app
    entrypoint: ["tail", "-f", "/dev/null"]
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-release
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
